Handle pipeline build status
bitrise-steplib/steps-github-status pull request #34
Opened 2023-03-10 11:14 UTC by godrei

### Checklist

- [x] I've read and followed the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- [x] `step.yml` and `README.md` is updated with the changes (if needed)

### Version

Requires a *MAJOR/MINOR/PATCH* [version update](https://semver.org/)

### Context

This PR adds support for Pipeline build status.

### Changes

- Handle `BITRISEIO_PIPELINE_BUILD_STATUS` with precedence over `BITRISE_BUILD_STATUS`.

2023-03-10 16:07 UTC, vshah23 requested changes

2023-03-10 16:07 UTC, vshah23 commented on main.go
> +	} else if pipelineBuildStatus == "failed" || pipelineBuildStatus == "aborted" {
I'm not a fan of this `else if` check since if we add more pipeline statuses in the future we have to come back and handle it here. Is it possible to handle it this way?: 
```
if (this is a pipeline build) {
  if (pipeline build successful) {
    return success
  }
  return failure
}
```

2023-03-13 11:39 UTC, miklosboros commented on main.go
> +	} else if pipelineBuildStatus == "failed" || pipelineBuildStatus == "aborted" {
How would you know whether it is successful or not without knowing about the status strings?

2023-03-13 13:37 UTC, vshah23 commented on main.go
> +	} else if pipelineBuildStatus == "failed" || pipelineBuildStatus == "aborted" {
We're still checking for success status but treating anything that's not a success as a failure.

2023-03-13 19:58 UTC, miklosboros commented on main.go
> +	} else if pipelineBuildStatus == "failed" || pipelineBuildStatus == "aborted" {
Sorry, I misunderstood your first comment. We could do that of course. There will be another change here tomorrow, I will do this with that change.

2023-03-14 12:29 UTC, godrei reviewed
@miklosboros looks good to me!
I just spotted that `BITRISE_BUILD_STATUS` is referenced directly, it would be great to wire in a step input for this config too.

2023-03-17 13:40 UTC, vshah23 submitted a review, later dismissed

2023-03-20 13:31 UTC, vshah23 approved these changes

2023-03-20 13:44 UTC, merged